import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import Head from "next/head";
import Image from "next/image";
import React, { Fragment, useState } from "react";
import { toast } from "react-toastify";

function Cron() {
  const [selectedFiles, setSelectedFiles] = useState([]);
  const [previewImg, setPreviewImg] = useState([]);

  const handleImages = async (e) => {
    let images = [];
    let sFiles = [];

    sFiles.push(e.target.files[0]);
    images.push(URL.createObjectURL(e.target.files[0]));
    setSelectedFiles(sFiles);
    setPreviewImg(images);
  };

  const sendCron = () => {
    toast.success("Cron has been sent successfully!");
  };

  return (
    <>
      <Head>
        <title>Centralized OPL</title>
        <meta name="description" content="Generated by Centralized OPL" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="d-flex flex-column flex-root">
          <div className="page d-flex flex-row flex-column-fluid">
            <SideBar />
            <div className="wrapper d-flex flex-column flex-row-fluid">
              <Header title={"Cron"} />
              <div
                className="content d-flex flex-column flex-column-fluid"
                id="kt_content"
              >
                <div className="post d-flex flex-column-fluid">
                  <div id="kt_content_container" className="container-xxl">
                    <div className="row g-5 g-xl-8">
                      <div className="col-md-6 col-12">
                        <div className="screen_header shadow">
                          <h1>Send CRON</h1>
                          <div className="pt-5">
                            <label htmlFor="cronImg">Cron Image</label>
                            <input
                              type="file"
                              className="form-control pb-2"
                              id="cronImg"
                              accept=".jpg, .png, .jpeg, .webp"
                              onChange={(e) => handleImages(e)}
                              multiple={false}
                            />
                            {previewImg && previewImg.length > 0 && (
                              <div className="previewDiv shadow">
                                {previewImg.map((item, index) => (
                                  <Fragment key={index}>
                                    <div className="previewImg">
                                      <Image
                                        src={item}
                                        alt="preview image"
                                        width={200}
                                        height={100}
                                      />
                                    </div>
                                  </Fragment>
                                ))}
                              </div>
                            )}
                            <div className="text-start py-3">
                              <button
                                onClick={sendCron}
                                className="btn fw-bold btn-primary"
                              >
                                SEND Cron
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default Cron;
