import Head from "next/head";
import Image from "next/image";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";
import { getDateTimeNow } from "@/utils/getDateTimeNow";
import React, { use, useEffect, useState } from "react";
import Select from "react-select";
import makeAnimated from "react-select/animated";
import { useSelector } from "react-redux";
import { deleteAPI, getAPI, postAPI } from "@/utils/fetchAPIs";
import { useRouter } from "next/router";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPen, faTrash } from "@fortawesome/free-solid-svg-icons";
import { toast } from "react-toastify";
import swal from "sweetalert";

const animatedComponents = makeAnimated();

export default function RelManagement() {
  const router = useRouter();
  const { loginToken } = useSelector((state) => state.authReducer);
  const [screenData, setScreenData] = useState(null);
  const [opls, setOpls] = useState([]);

  useEffect(() => {
    (async function () {
      let token = { loginToken };
      let isAuth = await postAPI("isAuth", token, null);
      if (!isAuth?.status) {
        router.push("/login");
      }
    })();
  }, [loginToken, router]);

  const getOPLs = async () => {
    let oplManages = await getAPI("relManagement", null);

    if (oplManages.status) {
      setOpls(oplManages.data);
    }
  };
  useEffect(() => {
    (async () => {
      await getOPLs();
    })();
  }, []);

  const deleteHandler = async (item) => {
    swal({
      title: "Are you sure?",
      text: "Once deleted, you will not be able to recover this OPL!",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    }).then(async (willDelete) => {
      if (willDelete) {
        const data = await deleteAPI(`addOPL?id=${item.id}`, null);
        if (data?.status) {
          swal("Poof! Your OPL has been deleted!", {
            icon: "success",
          });
          await getOPLs();
        } else {
          swal("OPL is not deleted. Try Again!");
        }
      } else {
        swal("Your OPL is safe!");
      }
    });
  };

  return (
    <>
      <Head>
        <title>Centralized OPL</title>
        <meta name="description" content="Generated by Centralized OPL" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="d-flex flex-column flex-root">
          <div className="page d-flex flex-row flex-column-fluid">
            <SideBar />
            <div className="wrapper d-flex flex-column flex-row-fluid">
              <Header />
              <div
                className="content d-flex flex-column flex-column-fluid"
                id="kt_content"
              >
                <div className="post d-flex flex-column-fluid">
                  <div id="kt_content_container" className="container-xxl">
                    <div className="row g-5 g-xl-8">
                      <div className="col-12">
                        <div className="card card-xxl-stretch mb-5 mb-xxl-8">
                          <div className="card-header border-0 pt-5">
                            <h3 className="card-title align-items-start flex-column">
                              <span className="card-label fw-bold fs-3 mb-1">
                                OPL Management
                              </span>
                              {/* <span className="text-muted mt-1 fw-semibold fs-7">
                                Total 400 Product Parts
                              </span> */}
                            </h3>
                            <Link
                              href="/relmanage-add"
                              className="btn fw-bold btn-primary"
                            >
                              Add New
                            </Link>
                          </div>
                          <div className="card-body py-3">
                            <div className="tab-content">
                              <div className="table-responsive">
                                <table className="table table-striped table-bordered">
                                  <thead>
                                    <tr className="border-0">
                                      <th>Client</th>
                                      <th>Product | Shift</th>
                                      <th>Product Part Name</th>
                                      <th className="min-w-200px">
                                        Instruction
                                      </th>
                                      <th>Screens</th>
                                      <th>Action</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    {opls &&
                                      opls.length > 0 &&
                                      opls.map((item, index) => (
                                        <tr key={index}>
                                          <td>{item?.client_name}</td>
                                          <td>
                                            {item?.product} | {item?.shift}
                                          </td>
                                          <td className="fw-semibold">
                                            {item?.parts}
                                          </td>
                                          <td className="min-w-200px">
                                            <Image
                                              loader={({ src }) => {
                                                return `uploads/${src}`;
                                              }}
                                              src={item?.opl}
                                              alt=""
                                              width={180}
                                              height={90}
                                            />
                                          </td>
                                          <td>{item?.screen}</td>
                                          <td>
                                            <Link
                                              href={`/relmanage-edit?r_id=${item?.id}`}
                                              className="btn btn-icon btn-light btn-active-color-primary btn-sm me-1"
                                            >
                                              <FontAwesomeIcon icon={faPen} />
                                            </Link>
                                            <button
                                              onClick={() =>
                                                deleteHandler(item)
                                              }
                                              className="btn btn-icon btn-light btn-active-color-primary btn-sm me-1"
                                            >
                                              <FontAwesomeIcon icon={faTrash} />
                                            </button>
                                          </td>
                                        </tr>
                                      ))}
                                  </tbody>
                                </table>
                                {/* <div className="text-center py-3">
                                  <button className="btn fw-bold btn-primary">
                                    SAVE
                                  </button>
                                </div> */}
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
